Update install-lubuntu-setup

diff --git a/install-lubuntu-setup b/install-lubuntu-setup
--- a/install-lubuntu-setup
+++ b/install-lubuntu-setup
@@ -5,18 +5,19 @@ sudo apt update
 sudo add-apt-repository -y ppa:teejee2008/ppa
 sudo apt-get update
 sudo apt-get -y install timeshift
-sudo apt install -y git
-git clone https://github.com/JasonMayberry/System # Download Lubuntu-Setup
-sudo cp -v ~/System/etc/timeshift.json /etc/timeshift.json
-sudo chown -c root:root /etc/timeshift.json
-sudo chmod -c 644 /etc/timeshift.json
-# Tell Timeshift to take a snapshot of everything before the rest of this script runs.
-sudo timeshift --create --yes
-echo "########################################################"
-echo "###   Timeshift created a snapshot so that you can   ###"
-echo "###   rolback the changes this script is making!     ###"
-echo "########################################################"
-sleep 5
+
+timeshift-launcher 2> /dev/null
+
+whiptail --yesno "Did you enable a snapshot of all files (/ and /home)? Did you create a full snapshot with Timeshift? You should! Timeshift can create a snapshot so that you can rolback the changes this script will be making! Do you want to continue:" --yes-button "Yes, I do" --no-button "No, I want to abort script!"  10 90
+CHOICE=$?
+if [[ $CHOICE == 0 ]]; then
+    echo "Yes"
+elif [[ $CHOICE == 1 ]]; then
+    echo "No, Aborting...."
+    sleep 3
+    exit
+fi
+
 echo "Preparing to install sublime-text"
 sudo apt install -y apt-transport-https ca-certificates curl software-properties-common
 curl -fsSL https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add -
@@ -38,7 +39,7 @@ sudo apt update
 sudo apt -y upgrade
 # 
 # Background
-sudo apt install -y zeitgeist gcc-7-locales python-gobject-2-dbg python-gtk2-doc icc-profiles glew-utils libtiff-opengl librole-tiny-perl perl-tk preload highlight
+sudo apt install -y zeitgeist gcc-7-locales python-gobject-2-dbg python-gtk2-doc icc-profiles glew-utils libtiff-opengl librole-tiny-perl perl-tk preload highlight git
 # Internet
 sudo apt install -y chromium-browser chromium-chromedriver links2 
 # Office
@@ -94,6 +95,7 @@ sudo apt -y autoremove
 # Settings
 sudo ufw enable # enable the firewall
 
+git clone https://github.com/JasonMayberry/System # Download Lubuntu-Setup
 # Install Lubuntu-Setup
 cp -vp ~/System/configs/.bash_aliases ~/.bash_aliases
 cp -vp ~/System/configs/.bash_aliases.bak ~/.bash_aliases.bak
